[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "siin-trainer"
version = "0.1.0"
description = "A generic Python library to train AI models on custom datasets."
authors = [
    { name="Siin Lab", email="contact@siinlab.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11,<3.13"
keywords = ["AI", "machine learning", "model training", "custom datasets"]
dependencies = [
    "click",
    "lgg",
    "tqdm",
    "pyyaml",
    "requests",
    "numpy",
    "ultralytics",
    "wandb>=0.21.0",
    "rfdetr[metrics]>=1.2.1",
    "clip",
    "rich",
    "streamlit",
]

[project.optional-dependencies]
dev = ["ruff"]

[project.scripts]
siin-trainer = "trainer.cli:main"

[tool.setuptools.packages.find]
where = ["."]

[tool.uv.sources]
clip = { git = "https://github.com/openai/CLIP.git", rev = "d05afc436d78f1c48dc0dbf8e5980a9d471f35f6" }